### PR TITLE
 Fade-out items while waiting for a delete to go through 

### PR DESCRIPTION
**Pull request by DanielHeath**
I've left a couple of other commits in but let me know if you'd prefer them sent separately.

This instantly fades-out any list item while it's being deleted, making the page feel a bit more responsive.

### CODE REVIEW

**Comment by schollz** [comment]
@DanielHeath This is amazing! I love your changes, thanks!!

**Comment by DanielHeath** [comment]
Oops - I added a few things accidentally not realizing I'd made this PR off my master branch.

In particular:

 * `.gitignore` should have `cowyo` and `dist` on separate lines, not `cowyodist`
 * `make linux64` should not try and deploy to my personal VPS
 * Debugging log statements I removed may or may not actually be needed

**Comment by schollz** [comment]
Oops, no problem, I'll take care of that!

**Comment by DanielHeath** [comment]
https://github.com/schollz/cowyo/pull/103 should do the gitignore stuff.

**Pull request merged**
