### PR TITLE
Implement file upload / download, fix #77

### LINKED ISSUE #77: Local inline images
Hi together..
Just read in the c't from cowyo, which is really great!
But I have a question: Linking images by http-path works fine. Is there a way to link local files or better: refer to images relative to the .exe path?
Thanks
Florian

### PR DESCRIPTION
**Pull request by DanielHeath**

### CODE REVIEW

**Comment by schollz** [comment]
Is there a way to make file upload/download optional? I don't want to allow it on the public server because I don't want to be responsible for hosting people's images.

Otherwise, its really really great!! Thanks.

**Comment by DanielHeath** [comment]
I’ve kept that in mind - it’s only enabled with a flag and is off by default.

Thanks,
Daniel Heath

**Comment by DanielHeath** [comment]
I've rebased this so it should merge cleanly.

**Comment by schollz** [comment]
Thanks, didn't mean to do that to you! Thanks so much for this update, it's really cool!

**Pull request merged**
